package com.hieuminh.utils;


import com.hieuminh.constant.CustomMessages;
import com.hieuminh.constant.SystemConstant;
import com.hieuminh.dto.BillDTO;
import com.hieuminh.dto.DetailBillDTO;
import com.hieuminh.entity.BillEntity;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.FontSelector;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

@Component
public class PdfPoiUtil {

    @Value("${dir.default_2}")
    private String dirDefault;


  /*  File fontFile = new File("arialuni.ttf");
    BaseFont unicode = BaseFont.createFont(
            fontFile.getAbsolutePath(), BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
*/




    public void addMetaData(Document document, Integer Tittle) {
        document.addTitle("Bill_of_"+Tittle);
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Hieu Minh");
        document.addCreator("Hieu Minh");
    }
    public void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    public void addTitlePage(Document document, String nameCreate, List<DetailBillDTO> items)
            throws DocumentException, IOException {

        final String  FONT = SystemConstant.BASE_DIR+"/font/TIMES.ttf";
        BaseFont bf = BaseFont.createFont(FONT,
                BaseFont.IDENTITY_H, true);

          Font catFont = new Font(bf, 18,
                Font.BOLD);
          Font redFont = new Font(bf, 12,
                Font.BOLD, BaseColor.RED);
          Font blueFont = new Font(bf, 18,
                Font.NORMAL, BaseColor.BLUE);
          Font subFont = new Font(bf, 16,
                Font.BOLD);
          Font smallBold = new Font(bf, 12,
                Font.BOLD);


        Paragraph preface = new Paragraph();
        Paragraph preface2 = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header

        String filename = SystemConstant.BASE_DIR+SystemConstant.PRODUCT_PROFILE+"/"+"logo.png";
        Image image = Image.getInstance(filename);
        image.setAlignment(Element.ALIGN_CENTER);
        document.add(image);
        addEmptyLine(preface, 3);
        preface2.add(new Paragraph(CustomMessages.NAME_STORE, blueFont));
        preface2.setAlignment(Element.ALIGN_CENTER);
        document.add(preface2);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + nameCreate + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 2);
        preface.add(new Paragraph(
                CustomMessages.CODE_BILL+": "+ items.get(0).getIdDetailBillBillEntity().getIdBill(),
                smallBold));
        preface.add(new Paragraph(
                CustomMessages.NAME_CUSTOMER+": "+items.get(0).getIdDetailBillBillEntity().getIdUserEntity().getNameFull(),
                smallBold));
        preface.add(new Paragraph(
                CustomMessages.PHONE+": "+items.get(0).getIdDetailBillBillEntity().getPhoneNumber(),
                smallBold));
        preface.add(new Paragraph(
                CustomMessages.PLACE+": "+items.get(0).getIdDetailBillBillEntity().getPlace(),
                smallBold));
        preface.add(new Paragraph(
                CustomMessages.DATE_TIME+": "+items.get(0).getIdDetailBillBillEntity().getDateTime(),
                smallBold));
        addEmptyLine(preface, 1);
        for (int i=0;i<items.size();i++){
            preface.add(new Paragraph(
                    CustomMessages.NAME_PRODUCT+": "+items.get(i).getIdDBillProductEntity().getNameProduct()+" - "+CustomMessages.COMAPRE+": "+items.get(i).getCount(),
                    smallBold
            ));
            addEmptyLine(preface, 1);
        }
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        String cost = currencyVN.format(items.get(0).getIdDetailBillBillEntity().getCost());
        preface.add(new Paragraph(
                CustomMessages.COST+": "+cost+"",
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "Thank you are belive we agreement with myeverything.com.",
                redFont));
        preface.setAlignment(Element.ALIGN_MIDDLE);
        document.add(preface);
    }
}
